# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "RMS Size Helper"
client_id = "154f1d77bd75ca9d8a0c638bcc64059c"
application_url = "https://size-helper.reedmace.net"
embedded = true

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [
  "https://size-helper.reedmace.net/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/api/webhooks/app/uninstalled"

# Mandatory GDPR compliance webhooks
[webhooks.privacy_compliance]
customer_deletion_url = "/api/webhooks/customers/redact"
customer_data_request_url = "/api/webhooks/customers/data_request"
shop_deletion_url = "/api/webhooks/shop/redact"

[app_proxy]
url = "/api/public"
subpath = "size-helper"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "reedmace-3.myshopify.com"
